/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecordingRouteImport } from './routes/recording'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ImportRouteImport } from './routes/import'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TranscriptionIdRouteImport } from './routes/transcription/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingRoute = RecordingRouteImport.update({
  id: '/recording',
  path: '/recording',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptionIdRoute = TranscriptionIdRouteImport.update({
  id: '/transcription/$id',
  path: '/transcription/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/recording': typeof RecordingRoute
  '/settings': typeof SettingsRoute
  '/transcription/$id': typeof TranscriptionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/recording': typeof RecordingRoute
  '/settings': typeof SettingsRoute
  '/transcription/$id': typeof TranscriptionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/library': typeof LibraryRoute
  '/recording': typeof RecordingRoute
  '/settings': typeof SettingsRoute
  '/transcription/$id': typeof TranscriptionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/library'
    | '/recording'
    | '/settings'
    | '/transcription/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/library'
    | '/recording'
    | '/settings'
    | '/transcription/$id'
  id:
    | '__root__'
    | '/'
    | '/import'
    | '/library'
    | '/recording'
    | '/settings'
    | '/transcription/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportRoute: typeof ImportRoute
  LibraryRoute: typeof LibraryRoute
  RecordingRoute: typeof RecordingRoute
  SettingsRoute: typeof SettingsRoute
  TranscriptionIdRoute: typeof TranscriptionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recording': {
      id: '/recording'
      path: '/recording'
      fullPath: '/recording'
      preLoaderRoute: typeof RecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcription/$id': {
      id: '/transcription/$id'
      path: '/transcription/$id'
      fullPath: '/transcription/$id'
      preLoaderRoute: typeof TranscriptionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportRoute: ImportRoute,
  LibraryRoute: LibraryRoute,
  RecordingRoute: RecordingRoute,
  SettingsRoute: SettingsRoute,
  TranscriptionIdRoute: TranscriptionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
